### ISSUE TITLE
Multiple alert_contact make back and forth changes

### ISSUE THREAD

**Issue by johanfleury** [vexxhost/terraform-provider-uptimerobot#1]
When there are multiple `alert_contact` on a monitor, terraform shows an difference between local and remote configurations.

The changes goes back and forth with `id`’s value switching from one `alert_contact` to another:

```
# First run
      ~ alert_contact {
          ~ id         = "XXX" -> "YYY"
            recurrence = 0
            threshold  = 0
        }
      ~ alert_contact {
          ~ id         = "YYY" -> "XXX"
            recurrence = 0
            threshold  = 0
        }

# Second run
      ~ alert_contact {
          ~ id         = "YYY" -> "XXX"
            recurrence = 0
            threshold  = 0
        }
      ~ alert_contact {
          ~ id         = "XXX" -> "YYY"
            recurrence = 0
            threshold  = 0
        }
```

This was supposedly fixed in https://github.com/louy/terraform-provider-uptimerobot/pull/97, but it doesn’t seem to work.

Current workaround is to setup a lifecycle to ignore those changes:

```
lifecycle {
  ignore_changes = [alert_contact[0].id, alert_contact[1].id]
}
```

Related:
* https://github.com/louy/terraform-provider-uptimerobot/pull/97
* https://github.com/louy/terraform-provider-uptimerobot/issues/85

**Comment by mnaser** [comment]
I wonder if the issue is because the API doesn't return them in an ordered manner, I'm looking at the other previous PRs.

Do you have a reproducer case that we can put into the acceptance tests and then simulate the failure in order to test if whatever fix we put in place works?

**Comment by johanfleury** [comment]
My configuration looks something like this (I removed confidential data):

```
terraform {
  required_version = "~> 1.0.0"

  required_providers {
    uptimerobot = {
      source  = "vexxhost/uptimerobot"
      version = "~> 0.6.1"
    }
  }

  backend "s3" {
    [SNIPPED]
  }
}

provider "uptimerobot" {
}

resource "uptimerobot_alert_contact" "slack" {
  friendly_name = "slack"
  type          = "slack"
  value         = "https://hooks.slack.com/services/[SNIPPED]"
}

resource "uptimerobot_alert_contact" "pagerduty" {
  friendly_name = "PagerDuty"
  type          = "email"
  value         = "[SNIPPED]@[SNIPPED].pagerduty.com"
}

resource "uptimerobot_alert_contact" "email" {
  friendly_name = "test@example.com"
  type          = "email"
  value         = "test@example.com"
}

resource "uptimerobot_monitor" "website" {
  friendly_name = "example.com"
  type          = "http"
  url           = "example.com"
  interval      = 300

  alert_contact {
    id         = uptimerobot_alert_contact.email.id
    threshold  = 0
    recurrence = 0
  }

  alert_contact {
    id         = uptimerobot_alert_contact.slack.id
    threshold  = 0
    recurrence = 0
  }

  alert_contact {
    id         = uptimerobot_alert_contact.pagerduty.id
    threshold  = 0
    recurrence = 0
  }
}
```

Strangely, it’s only the last two alert contacts (slack and pagerduty) that change back and forth.

**Comment by johanfleury** [comment]
Not sure if that would be a suitable solution, but maybe we could use [TypeSet](https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset) instead of [TypeList](https://www.terraform.io/docs/extend/schemas/schema-types.html#typelist) in resource_uptimerobot_monitor.go#L89: https://github.com/vexxhost/terraform-provider-uptimerobot/blob/33a5e27b34d6a29edeb2be516256c0d187cc5b07/internal/provider/resource_uptimerobot_monitor.go#L88-L90.

**Comment by johanfleury** [comment]
If I make a PR, will acceptance tests run automatically?
