### ISSUE TITLE
Perpetual diff with `http_method`

### ISSUE THREAD

**Issue by z0rc** [vexxhost/terraform-provider-uptimerobot#17]
```tf
resource "uptimerobot_monitor" "test" {
  friendly_name = "Test"
  type          = "http"
  url           = "https://google.com"
}
```

After apply `terraform plan` still shows diff:
```
  # uptimerobot_monitor.test will be updated in-place
  ~ resource "uptimerobot_monitor" "test" {
      + http_method         = "GET"
        id                  = "791412888"
        # (8 unchanged attributes hidden)
    }
```

Consequent applies don't resolve this diff and it's always present.

**Comment by z0rc** [comment]
Probably related to https://github.com/vexxhost/terraform-provider-uptimerobot/pull/12

**Comment by mnaser** [comment]
Yep, it looks like `http_method` is not returned by the UptimeRobot API.  I've reported that to them but don't know how quickly they will solve.

I'll workaround it by assuming whatever is in the state is the correct/valid value, if that's possible.  It's not ideal, but eh.
